apiVersion: v1 
kind: Service
metadata:
  name: events-ui-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: demo-ui
    env: dev
  type: LoadBalancer

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: my-autoscaler
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: my-deployment
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60

